version: "1.0"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    container_name: psql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    networks: 
      - clickhouse
    volumes:
      - ./postgres/source/aDDL_source.sql:/docker-entrypoint-initdb.d/aDDL_source.sql
      - ./postgres/source/aDML_source.sql:/docker-entrypoint-initdb.d/aDML_source.sql
      - ./postgres/core/bDDL_core.sql:/docker-entrypoint-initdb.d/bDDL_core.sql
      - ./postgres/core/bDML_core.sql:/docker-entrypoint-initdb.d/bDML_core.sql
      - ./postgres/mart/cmart.sql:/docker-entrypoint-initdb.d/cmart.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db"]
      interval: 5s
      retries: 5
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144 
    ports:  
      - "8123:8123"
    volumes:
      - ./clickhouse/scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
      - "clickhouse-data:/var/lib/clickhouse"

  click-ui:
    image: spoonest/clickhouse-tabix-web-client
    networks:
        - clickhouse
    depends_on:
      - clickhouse
    ports:
      - "8124:80"
    restart: always
volumes:
  clickhouse-data:
networks:
    clickhouse: